continue
user.errors
user.valid?
user
continue
session['devise.linkedin_data'] = request.env['omniauth.auth'].except('extra')
session['devise.linkedin_data' = request.env['omniauth.auth'].except('extra')
request.env['omniauth.auth'].except('extra')
request.env['omniauth.auth']
session['devise.linkedin_data']
session.count
session
continue
a.info.industry
a.info
a = request.env['omniauth.auth']
